version: '3'
networks:
  monreseau:
    external: false

# Définition des services (conteneurs) à déployer
services:

  # Premier serveur web
  web:
     build: . 
    # Utilise l'image Nginx dans sa dernière version
    # Nom du conteneur
     container_name: monsiteweb
     volumes:
      -monsitestatics:/app/static_assets/
      - monsitemedias:/app/medias/
     depends_on:
      - db 
    # Réseaux auxquels le conteneur est connecté et leurs adresses IP respectives
     networks:
       - monreseau
  db:
    image: 'postgres:latest'
    container_name: monsitedb
    environment:
      POSTGRES_PASSWORD: mypass
    volumes:
      - pgdb:/var:lib/postgresql/data
    networks:
      - monreseau

  nginx:
    image: 'nginx:1.19-alpine'
    container_name: monsitenginx
    volumes:
      - monsitestatics:/home/app/web/static_assets
      - monsitemedias:/home/app/web/medias
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - monreseau
    ports:
      - "80:80"
  volumes:
    pgdb:
    monsitestatics:
    monsitemedias: